[package]
name = "campus-web-login"
version = "0.1.0"
edition = "2021"
description = "Cross-platform campus network auto login"
license = "MIT"
repository = "https://github.com/quyansiyuanwang/NDKY-CampusNetLogin"
readme = "../README.md"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
num-bigint = "0.4"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "0.8"
url = "2"

[profile.release]
lto = true
strip = true

[profile.dist]
inherits = "release"
