#!/usr/bin/env node
const fs=require('fs'), http=require('http'), https=require('https'), crypto=require('crypto');
function parseSimple(text, yaml=false){const o={}; for(const line of text.split(/\r?\n/)){const m=yaml?/^\s*([\w_]+):\s*["']?(.*?)["']?\s*$/.exec(line):/^\s*([\w_]+)\s*=\s*["']?(.*?)["']?\s*$/.exec(line); if(m)o[m[1]]=m[2];} return o;}
function config(){const arg=process.argv.indexOf('--config'); const p=arg>0?process.argv[arg+1]:fs.existsSync('config.toml')?'config.toml':fs.existsSync('config.yaml')?'config.yaml':'config.yml'; if(!p||!fs.existsSync(p))throw Error('配置文件不存在'); const o=parseSimple(fs.readFileSync(p,'utf8'),/\.ya?ml$/.test(p)); if(!o.username||!o.password||!o.base_url)throw Error('username、password、base_url 不能为空'); o.check_interval=+o.check_interval||5;o.request_retries=+o.request_retries||3;return o;}
function req(url,method='GET',body){return new Promise((resolve,reject)=>{const u=new URL(url), mod=u.protocol==='https:'?https:http, r=mod.request(u,{method,headers:{'User-Agent':'CampusWebLogin/0.1',...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{})}},res=>{let b='';res.on('data',x=>b+=x);res.on('end',()=>resolve({res,body:b,url}));});r.on('error',reject);r.setTimeout(10000,()=>r.destroy(Error('请求超时')));if(body)r.write(body);r.end();});}
async function follow(url){for(let i=0;i<10;i++){const x=await req(url);if(x.res.statusCode>=300&&x.res.statusCode<400&&x.res.headers.location){url=new URL(x.res.headers.location,url).href;continue;}return x;}throw Error('重定向次数过多');}
function query(html){const m=/location\.href\s*=\s*["']([^"']+)["']/i.exec(html);return m?new URL(m[1]).search.slice(1):'';}
async function fetchCfg(c){const p=await follow(c.base_url),q=query(p.body),r=await req(c.base_url.replace(/\/$/,'')+'/eportal/InterFace.do?method=pageInfo','POST','queryString='+encodeURIComponent(q));const j=JSON.parse(r.body);return {q,m:j.publicKeyModulus,e:j.publicKeyExponent||'10001'};}
function rsa(p,m,e){const n=BigInt('0x'+m), ex=BigInt('0x'+e), b=Buffer.from([...p].reverse().join(''),'utf8'), size=Math.max(2,Math.floor((n.toString(2).length+7)/8)-2), out=[];for(let i=0;i<b.length;i+=size){let z=Buffer.alloc(size);b.copy(z,0,i,Math.min(i+size,b.length));let x=BigInt('0x'+z.toString('hex'));let y=1n,a=x,k=ex;while(k){if(k&1n)y=y*a%n;a=a*a%n;k>>=1n;}out.push(y.toString(16));}return out.join(' ');}
async function main(){const c=config(),cmd=process.argv.find(x=>['run','check','fetch-config'].includes(x))||'run';if(cmd==='check'){const x=await req(c.connectivity_test_url||'http://www.msftconnecttest.com/connecttest.txt');console.log(x.res.statusCode===200&&x.body.trim()==='Microsoft Connect Test'?'online':'offline');return;}if(cmd==='fetch-config'){console.log(await fetchCfg(c));return;}const once=process.argv.includes('--once');do{const x=await req(c.connectivity_test_url||'http://www.msftconnecttest.com/connecttest.txt');if(!(x.res.statusCode===200&&x.body.trim()==='Microsoft Connect Test')){const f=await fetchCfg(c), data=new URLSearchParams({userId:c.username,password:rsa(c.password,f.m,f.e),service:c.service||'',queryString:f.q,passwordEncrypt:'true'});const r=await req(c.base_url.replace(/\/$/,'')+'/eportal/InterFace.do?method=login','POST',data.toString());console.log(r.body);}else console.log('网络正常');if(!once)await new Promise(r=>setTimeout(r,c.check_interval*1000));}while(!once);}
main().catch(e=>{console.error(e.message);process.exit(1)});
